{{- if .Values.worker.enabled }}

{{- range $jobName, $job := .Values.worker.cronjobs }}

{{- if $job.enabled }}

---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: "{{ template "ifrcgo-risk-module.fullname" $ }}-{{ $jobName | nospace | lower | replace "_" "-" }}"
  labels:
    app.kubernetes.io/name: {{ include "ifrcgo-risk-module.fullname" $ }}
    app.kubernetes.io/component: {{ include "ifrcgo-risk-module.fullname" $ }}-api-jobs
    environment: {{ $.Values.environment }}
    release: {{ $.Release.Name }}
spec:
  schedule: {{ $job.schedule | quote }}
  concurrencyPolicy: "Forbid"
  jobTemplate:
    spec:
      activeDeadlineSeconds: {{ default 7200 $job.timeLimit }}  # 2 hours default TODO: Lower this
      template:
        spec:
          restartPolicy: "Never"
          containers:
            - name: "{{ template "ifrcgo-risk-module.fullname" $ }}-{{ $jobName | nospace | lower | replace "_" "-" }}"
              image: "{{ $.Values.image.name }}:{{ $.Values.image.tag }}"
              command: ["./manage.py", "{{ $jobName }}"]
              resources:
                {{- toYaml (default $.Values.worker.defaultResources $job.resources) | nindent 16 }}
              envFrom:
                - secretRef:
                    name: {{ include "ifrcgo-risk-module.secretname" $ }}
                - configMapRef:
                    name: {{ template "ifrcgo-risk-module.fullname" $ }}-api-configmap
          {{- with $.Values.imagePullSecrets }}
          imagePullSecrets:
            {{- toYaml . | nindent 12 }}
          {{- end }}

{{- end }}

{{- end }}

{{- end }}
