{{- if .Values.api.enabled }}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ifrcgo-risk-module.fullname" . }}-api
  labels:
    app.kubernetes.io/name: {{ include "ifrcgo-risk-module.fullname" . }}
    app.kubernetes.io/component: {{ include "ifrcgo-risk-module.fullname" . }}-api
    environment: {{ .Values.environment }}
    release: {{ .Release.Name }}
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  replicas: {{ .Values.api.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "ifrcgo-risk-module.fullname" . }}
      app.kubernetes.io/component: {{ include "ifrcgo-risk-module.fullname" . }}-api
  template:
    metadata:
      {{- if not .Values.azure.aksSecretsProviderAvailable }}
      annotations:
        checksum/secret: {{ include (print .Template.BasePath "/config/secret.yaml") . | sha256sum }}
        checksum/configmap: {{ include (print .Template.BasePath "/config/configmap.yaml") . | sha256sum }}
      {{- end }}
      labels:
        app.kubernetes.io/name: {{ include "ifrcgo-risk-module.fullname" . }}
        app.kubernetes.io/component: {{ include "ifrcgo-risk-module.fullname" . }}-api
    spec:
      containers:
        - name: {{ include "ifrcgo-risk-module.fullname" . }}-api
          image: "{{ .Values.image.name }}:{{ .Values.image.tag }}"
          command: ["bash", "/code/scripts/run_prod.sh"]
          ports:
            - name: http
              containerPort: {{ .Values.api.containerPort }}
              protocol: TCP
          # livenessProbe: # TODO: Add Liveness Probe
          envFrom:
            - secretRef:
                name: {{ template "ifrcgo-risk-module.secretname" . }}
            - configMapRef:
                name: {{ template "ifrcgo-risk-module.fullname" . }}-api-configmap
          resources:
            {{- toYaml .Values.api.resources | nindent 12 }}
          {{- if .Values.azure.aksSecretsProviderAvailable }}
          volumeMounts:
            - name: {{ include "ifrcgo-risk-module.secretname" . }}
              mountPath: /mnt/secrets-store
              readOnly: true
          {{- end }}

      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}

      {{- if .Values.serviceAccount.create }}
      serviceAccountName: {{ include "ifrcgo-risk-module.serviceAccountName" . }}
      {{- end }}

      {{- if .Values.azure.aksSecretsProviderAvailable }}
      volumes:
        - name: {{ include "ifrcgo-risk-module.secretname" . }}
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: {{ include "ifrcgo-risk-module.fullname" . }}-secret-provider
      {{- end }}

{{- end }}
