{{- if .Values.api.enabled -}}

apiVersion: v1
kind: Service
metadata:
  name: {{ template "ifrcgo-risk-module.fullname" . }}-api-svc
  labels:
    app.kubernetes.io/name: {{ include "ifrcgo-risk-module.fullname" . }}
    app.kubernetes.io/component: {{ include "ifrcgo-risk-module.fullname" . }}-api
    environment: {{ .Values.environment }}
    release: {{ .Release.Name }}
spec:
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: {{ include "ifrcgo-risk-module.fullname" . }}
    app.kubernetes.io/component: {{ include "ifrcgo-risk-module.fullname" . }}-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: {{ .Values.api.containerPort }}

{{- end }}
